version: "3.7"

services:
    traefik:
        image: "traefik:v2.1"
        container_name: "traefik"
        hostname: "traefik"
        env_file:
            - .env
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./traefik.yml:/traefik.yml:ro"
            - "./tccauley.dev.pem:/tccauley.dev.pem:ro"
            - "./tccauley.dev.key:/tccauley.dev.key:ro"
            - "./dynamic:/dynamic"
        labels:
            - "traefik.enable=true"
#  nginx:
#    image: nginx:1.17.8-alpine
#    container_name: nginx
#    hostname: nginx
#    ports:
#      - "50081:443"
#    volumes:
#      - "./default.conf:/etc/nginx/conf.d/default.conf"
#      - "./nginx/:/usr/share/nginx/html/graphql/"
#    labels:
#      - "traefik.enable=true"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
