http:
  routers:
    api:
      rule: "Host(`tccauley.dev`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      tls:
        certResolver: lets-encr
        domains:
          - main: "tccauley.dev"
            sans:
              - "*.tccauley.dev"
      entryPoints:
        - websecure
      service: api@internal
      middlewares:
        - auth

  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$apr1$hfxvyug9$Jl6u78o2ZQXCQeSUZ/dqV/"
