log:
    level: DEBUG

entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        watch: true
        exposedByDefault: false
        network: traefik_public
    #    tls:
    #      cert: tccauley.dev.pem
    #      key: tccauley.dev.key
    file:
        directory: "/dynamic"
        watch: true

api:
    dashboard: true
    debug: true

accessLog: {}

certificatesResolvers:
    letsencr:
        acme:
            email: clint.cauley@gmail.com
            caServer: https://acme-staging-v02.api.letsencrypt.org/directory
            storage: acme.json
            dnsChallenge:
                provider: cloudflare
                delayBeforeCheck: 0
