global:
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - job_name: prometheus
    scheme: http
    static_configs:
      - targets:
          - metrics:9090
  - job_name: grafana
    scheme: http
    static_configs:
      - targets:
          - grafana:3000
  - job_name: traefik
    scheme: http
    static_configs:
      - targets:
          - traefik:8080
  - job_name: statping
    bearer_token: "0d779cbe2db87f0383c26f271fd5441ff8661273"
    static_configs:
      - targets:
          - statping:8081
